"""update

Revision ID: 94984582f669
Revises: fa01d76a61f8
Create Date: 2024-12-09 14:29:55.741621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision: str = '94984582f669'
down_revision: Union[str, None] = 'fa01d76a61f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_others', sa.Boolean(), server_default=expression.false(), nullable=False, comment='清理其他文件'))
        batch_op.add_column(sa.Column('optimize_name', sa.Boolean(), server_default=expression.false(), nullable=False, comment='优化名字'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.drop_column('optimize_name')
        batch_op.drop_column('clean_others')

    # ### end Alembic commands ###
