"""rename table task

Revision ID: 5bb16376ea6f
Revises: d2fdac025143
Create Date: 2024-09-01 01:27:16.343596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb16376ea6f'
down_revision: Union[str, None] = 'd2fdac025143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('transfertask')
    except:
        pass
    try:
        op.rename_table('library', 'transfertask')
    except:
        op.create_table('transfertask')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('transfertask', 'library')
    # ### end Alembic commands ###
