"""add setting

Revision ID: f42c79602ca2
Revises: 4ac6e0d00009
Create Date: 2024-09-06 14:20:03.205064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42c79602ca2'
down_revision: Union[str, None] = '4ac6e0d00009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('scrapingsetting')
    except:
        pass
    try:
        op.rename_table('scrapingconfig', 'scrapingsetting')
    except:
        op.create_table('scrapingsetting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('scrapingsetting', 'scrapingconfig')
    # ### end Alembic commands ###
