"""task config

Revision ID: 440552a7d45d
Revises: 5bb16376ea6f
Create Date: 2024-09-02 22:32:39.341684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440552a7d45d'
down_revision: Union[str, None] = '5bb16376ea6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transfer_type', sa.Integer(), nullable=True))
        batch_op.drop_column('link_type')
        batch_op.drop_column('lib_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lib_type', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('link_type', sa.INTEGER(), nullable=True))
        batch_op.drop_column('transfer_type')
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
