"""update transfer task

Revision ID: d39dc4d06e81
Revises: f42c79602ca2
Create Date: 2024-09-24 20:59:47.553550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39dc4d06e81'
down_revision: Union[str, None] = 'f42c79602ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.Integer(), nullable=True, comment='内容类型'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
