"""update

Revision ID: eca431b007aa
Revises: b0305c88a31f
Create Date: 2025-03-15 22:49:41.914135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca431b007aa'
down_revision: Union[str, None] = 'b0305c88a31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediaitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'))
        batch_op.add_column(sa.Column('updatetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'))
        batch_op.drop_index('ix_metadata_media_item_id')
        batch_op.drop_constraint('fk_metadata_media_item_id_mediaitem', type_='foreignkey')
        batch_op.drop_column('media_item_id')

    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'))

    with op.batch_alter_table('watchhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createtime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'))
        batch_op.add_column(sa.Column('updatetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updatetime')
        batch_op.drop_column('createtime')

    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('createtime')

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_item_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_metadata_media_item_id_mediaitem', 'mediaitem', ['media_item_id'], ['id'])
        batch_op.create_index('ix_metadata_media_item_id', ['media_item_id'], unique=False)
        batch_op.drop_column('createtime')

    with op.batch_alter_table('mediaitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updatetime')
        batch_op.drop_column('createtime')

    # ### end Alembic commands ###
