"""task operation enum

Revision ID: 76e162879568
Revises: c63121315121
Create Date: 2025-02-19 11:22:40.824093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e162879568'
down_revision: Union[str, None] = 'c63121315121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation',
                                      sa.Enum('HARD_LINK', 'SYMLINK', 'MOVE', 'COPY', name='operationmethod'),
                                      nullable=False,
                                      server_default='HARD_LINK'))
        batch_op.drop_column('task_type')
        batch_op.drop_column('transfer_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_type', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('task_type', sa.INTEGER(), nullable=True))
        batch_op.drop_column('operation')
    # ### end Alembic commands ###
