"""srcdeleted

Revision ID: f6497e8754c9
Revises: 5499b19d0194
Create Date: 2025-03-07 10:03:36.631762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6497e8754c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('transrecords', schema=None) as batch_op:
            batch_op.add_column(sa.Column('srcdeleted', sa.Boolean(), server_default='0', nullable=True, comment='实际源文件已经删除'))
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('transrecords', schema=None) as batch_op:
            batch_op.drop_column('srcdeleted')
    except:
        pass
    # ### end Alembic commands ###
