"""rename_scraping_setting_to_config

Revision ID: 0249fa33a003
Revises: 76e162879568
Create Date: 2025-03-05 09:31:10.044751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0249fa33a003'
down_revision: Union[str, None] = '76e162879568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 重命名表而不是创建新表，这样数据会保留
    op.rename_table('scrapingsetting', 'scrapingconfig')

    # 重命名索引
    with op.batch_alter_table('scrapingconfig', schema=None) as batch_op:
        batch_op.drop_index('ix_scrapingsetting_id')
        batch_op.create_index(batch_op.f('ix_scrapingconfig_id'), ['id'], unique=False)

    # TransferTask修改保留
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.alter_column('operation',
                              existing_type=sa.VARCHAR(length=9),
                              nullable=True,
                              existing_server_default=sa.text("'HARD_LINK'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚时重命名回原表名
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.alter_column('operation',
                              existing_type=sa.VARCHAR(length=9),
                              nullable=False,
                              existing_server_default=sa.text("'HARD_LINK'"))

    # 重命名索引
    with op.batch_alter_table('scrapingconfig', schema=None) as batch_op:
        batch_op.drop_index('ix_scrapingconfig_id')
        batch_op.create_index('ix_scrapingsetting_id', ['id'], unique=False)

    # 重命名表回原名
    op.rename_table('scrapingconfig', 'scrapingsetting')
    # ### end Alembic commands ###
