"""update task detail

Revision ID: cedc1ac28475
Revises: dd26783c5834
Create Date: 2025-06-30 19:59:20.209908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedc1ac28475'
down_revision: Union[str, None] = 'dd26783c5834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celerytask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(), nullable=True, comment='任务类型'))
        batch_op.add_column(sa.Column('detail', sa.String(), nullable=True, comment='任务详情'))
        batch_op.drop_index('ix_celerytask_task_name')
        batch_op.drop_column('task_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celerytask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_name', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_celerytask_task_name', ['task_name'], unique=False)
        batch_op.drop_column('detail')
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
