"""update runtime

Revision ID: c63121315121
Revises: aaa4935bf79d
Create Date: 2025-02-18 17:08:42.800863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63121315121'
down_revision: Union[str, None] = 'aaa4935bf79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime', sa.String(), nullable=True, server_default='', comment='时长'))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.drop_column('runtime')

    # ### end Alembic commands ###
