"""celery task

Revision ID: dd26783c5834
Revises: 33e3d6c5956c
Create Date: 2025-06-30 15:29:24.927584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd26783c5834'
down_revision: Union[str, None] = '33e3d6c5956c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celerytask',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.String(), nullable=True, comment='Celery任务ID'),
                    sa.Column('task_name', sa.String(), nullable=True, comment='任务名称'),
                    sa.Column('status', sa.Enum('PENDING', 'PROGRESS', 'SUCCESS', 'FAILURE',
                                                'REVOKED', name='taskstatus'), nullable=True, comment='任务状态'),
                    sa.Column('progress', sa.Float(), nullable=True, comment='进度百分比 (0-100)'),
                    sa.Column('step', sa.String(), nullable=True, comment='当前步骤描述'),
                    sa.Column('result', sa.String(), nullable=True, comment='任务结果'),
                    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
                    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
                    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('celerytask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_celerytask_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_celerytask_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_celerytask_task_name'), ['task_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celerytask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_celerytask_task_name'))
        batch_op.drop_index(batch_op.f('ix_celerytask_task_id'))
        batch_op.drop_index(batch_op.f('ix_celerytask_id'))

    op.drop_table('celerytask')
    # ### end Alembic commands ###
