"""update status

Revision ID: 33e3d6c5956c
Revises: 062f620c65b4
Create Date: 2025-06-29 23:03:00.514920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e3d6c5956c'
down_revision: Union[str, None] = '062f620c65b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True, comment='是否成功'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transrecords', schema=None) as batch_op:
        batch_op.drop_column('success')

    # ### end Alembic commands ###
