"""rename_transfer_task_to_config

Revision ID: 4e1deb8ef1bc
Revises: 0249fa33a003
Create Date: 2025-03-05 09:53:40.900536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1deb8ef1bc'
down_revision: Union[str, None] = '0249fa33a003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 重命名表而不是创建新表，这样数据会保留
    op.rename_table('transfertask', 'transferconfig')
    
    # 重命名索引
    with op.batch_alter_table('transferconfig', schema=None) as batch_op:
        batch_op.drop_index('ix_transfertask_id')
        batch_op.create_index(batch_op.f('ix_transferconfig_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 重命名索引
    with op.batch_alter_table('transferconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transferconfig_id'))
        batch_op.create_index('ix_transfertask_id', ['id'], unique=False)
    
    # 重命名表回原名
    op.rename_table('transferconfig', 'transfertask')
    # ### end Alembic commands ###
