"""watched

Revision ID: 07c8c5cb55d1
Revises: eca431b007aa
Create Date: 2025-03-15 23:15:40.402811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c8c5cb55d1'
down_revision: Union[str, None] = 'eca431b007aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watched', sa.Boolean(), server_default='0', nullable=True, comment='是否观看'))
        batch_op.add_column(sa.Column('watch_count', sa.Integer(), nullable=True, comment='观看次数'))
        batch_op.drop_column('played_at')
        batch_op.drop_column('play_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('play_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('played_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('watch_count')
        batch_op.drop_column('watched')

    # ### end Alembic commands ###
