"""downloads

Revision ID: aaa4935bf79d
Revises: fd1eee64adf4
Create Date: 2025-02-18 09:22:35.729937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa4935bf79d'
down_revision: Union[str, None] = 'fd1eee64adf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'))

    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False, comment='下载链接'),
    sa.Column('filepath', sa.String(), nullable=False, comment='文件路径'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.drop_column('updatetime')

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_id'))

    op.drop_table('downloads')
    # ### end Alembic commands ###
