"""add extrainfo 

Revision ID: fd1eee64adf4
Revises: 94984582f669
Create Date: 2025-02-13 15:24:13.467040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1eee64adf4'
down_revision: Union[str, None] = '94984582f669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extrainfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False, comment='文件路径'),
    sa.Column('number', sa.String(), nullable=False, comment='编号'),
    sa.Column('tag', sa.String(), nullable=True, comment='标签（用于分类）'),
    sa.Column('partNumber', sa.Integer(), nullable=True, comment='分集数'),
    sa.Column('specifiedsource', sa.String(), nullable=True, comment='指定来源'),
    sa.Column('specifiedurl', sa.String(), nullable=True, comment='指定链接'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extrainfo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extrainfo_id'), ['id'], unique=False)

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True, comment='时长（分钟）'))
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True, comment='类型'))
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True, comment='评级'))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True, comment='语言'))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True, comment='国家'))
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('release',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.alter_column('clean_others',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('optimize_name',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfertask', schema=None) as batch_op:
        batch_op.alter_column('optimize_name',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('clean_others',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('release',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('country')
        batch_op.drop_column('language')
        batch_op.drop_column('rating')
        batch_op.drop_column('genre')
        batch_op.drop_column('duration')

    with op.batch_alter_table('extrainfo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extrainfo_id'))

    op.drop_table('extrainfo')
    # ### end Alembic commands ###
