"""update extrainfo crop

Revision ID: 3aadc460e69a
Revises: cedc1ac28475
Create Date: 2026-01-03 15:57:59.211534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aadc460e69a'
down_revision: Union[str, None] = 'cedc1ac28475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrainfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop', sa.Boolean(), nullable=True, comment='是否裁切poster'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrainfo', schema=None) as batch_op:
        batch_op.drop_column('crop')

    # ### end Alembic commands ###
